### ISSUE TITLE
Use of the built-in url module for parsing the url.

### ISSUE THREAD

**Issue by jdalton** [TooTallNate/file-uri-to-path#2]
Hi @TooTallNate!

I'm evaluating this package and thought that it might benefit from using the built-in [url package](https://nodejs.org/api/url.html#url_url) from Node. Would you be up for a PR?

**Comment by jdalton** [comment]
Would you be up for a PR?

**Comment by TooTallNate** [comment]
I'm trying to figure out what would be the benefit exactly. Better compatibility, simpler code or what?

**Comment by jdalton** [comment]
Simpler code. Relying on something that's built-in (hammered on a bit more).

**Comment by TooTallNate** [comment]
It's been so long since I wrote this module, I'm trying to remember why I wouldn't have used `url` module in the first place 🤔 

I'd entertain a pull request!

**Comment by jdalton** [comment]
Moved to #3.
